In [114]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Section :- A

#### 1. Create a 5* 5 NumPy array values between 0 to 9.?

In [115]:
A = np.random.randint(10 , size=[5,5])
A

array([[6, 9, 4, 8, 6],
       [9, 1, 4, 6, 2],
       [2, 5, 5, 3, 3],
       [3, 9, 3, 5, 9],
       [4, 7, 0, 2, 1]])

#### 2. Print the data type of element of the array?

In [116]:
A.dtype

dtype('int32')

#### 3. Create a pandas dataframe from the python dictionary.

In [117]:
B = {
        'Name' : ['Ajay' , 'Avnish' , 'Joy' , 'Jockey'],
        'Roll No' : [5,7,10,3],
        'Age' : [21,25,19,22]
    }
C = pd.DataFrame(B)
C

Name  Roll No  Age
0    Ajay        5   21
1  Avnish        7   25
2     Joy       10   19
3  Jockey        3   22

#### 4. Add one more column in the above dataframe.

In [118]:
C['Division'] = 'A'
C

Name  Roll No  Age Division
0    Ajay        5   21        A
1  Avnish        7   25        A
2     Joy       10   19        A
3  Jockey        3   22        A

## Section :- B

#### 1. Load the fracture.csv data into pandas dataframe.

In [119]:
MDF = pd.read_csv('fracture.csv')
MDF

id        age sex     fracture  weight_kg  height_cm      medication  \
0      469  57.052768   F  no fracture       64.0      155.5  Anticonvulsant   
1     8724  75.741225   F  no fracture       78.0      162.0   No medication   
2     6736  70.778900   M  no fracture       73.0      170.5   No medication   
3    24180  78.247175   F  no fracture       60.0      148.0   No medication   
4    17072  54.191877   M  no fracture       55.0      161.0   No medication   
..     ...        ...  ..          ...        ...        ...             ...   
164  21892  77.982543   M     fracture       74.0      164.0   No medication   
165  24140  50.285303   F     fracture       59.0      161.0   No medication   
166   6969  46.359721   M     fracture       67.0      169.0   No medication   
167   5505  54.788368   M     fracture       70.0      166.0   No medication   
168     71  69.994822   F     fracture       68.5      165.0   No medication   

     waiting_time     bmd  
0              18  0.8793  
1              56  0.7946  
2              10  0.9067  
3              14  0.7112  
4              20  0.7909  
..            ...     ...  
164            49  0.7941  
165             6  0.7971  
166            10  0.8037  
167            14  0.8072  
168            25  0.8664  

[169 rows x 9 columns]

#### 2. Add new column named “bmi” to store Body Mass Index for each record.Formula to calculate BMI is: weight_kg / (height_cm/100)^2

In [120]:
MDF['bmi'] = MDF['weight_kg'] / (MDF['height_cm'] / 100) ** 2
MDF

id        age sex     fracture  weight_kg  height_cm      medication  \
0      469  57.052768   F  no fracture       64.0      155.5  Anticonvulsant   
1     8724  75.741225   F  no fracture       78.0      162.0   No medication   
2     6736  70.778900   M  no fracture       73.0      170.5   No medication   
3    24180  78.247175   F  no fracture       60.0      148.0   No medication   
4    17072  54.191877   M  no fracture       55.0      161.0   No medication   
..     ...        ...  ..          ...        ...        ...             ...   
164  21892  77.982543   M     fracture       74.0      164.0   No medication   
165  24140  50.285303   F     fracture       59.0      161.0   No medication   
166   6969  46.359721   M     fracture       67.0      169.0   No medication   
167   5505  54.788368   M     fracture       70.0      166.0   No medication   
168     71  69.994822   F     fracture       68.5      165.0   No medication   

     waiting_time     bmd        bmi  
0              18  0.8793  26.467882  
1              56  0.7946  29.721079  
2              10  0.9067  25.111583  
3              14  0.7112  27.392257  
4              20  0.7909  21.218317  
..            ...     ...        ...  
164            49  0.7941  27.513385  
165             6  0.7971  22.761468  
166            10  0.8037  23.458562  
167            14  0.8072  25.402816  
168            25  0.8664  25.160698  

[169 rows x 10 columns]

#### 3. Split the data set in to test and train in 30:70 ratio.

In [121]:
x = MDF[['age' , 'sex' , 'bmi' , 'bmd']]
y = MDF['fracture'].values

In [122]:
from sklearn.preprocessing import LabelEncoder
label_y = LabelEncoder()
y = label_y.fit_transform(y)


label_s = LabelEncoder()
x['sex'] = label_s.fit_transform(x['sex'])

C:\Users\VAIBHAV DARJI\AppData\Local\Temp\ipykernel_10396\4087404088.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['sex'] = label_s.fit_transform(x['sex'])


In [123]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size=0.3)

#### 4. Build a Naive Bias model to predict the fracture considering age, sex,bmi and bmd.

In [124]:
from sklearn.naive_bayes import GaussianNB
gaussian_model = GaussianNB()
gaussian_model.fit(x_train , y_train)
y_pred = gaussian_model.predict(x_test)

In [125]:
y_pred

array([0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1])

#### 5. Apply the model on to the test and train data. Plot the outcomes of prediction using appropriate graph.

#### 6. Calculate accuracy of the model using confusion matix.

In [126]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test , y_pred)

array([[11,  5],
       [ 6, 29]], dtype=int64)

In [129]:
40/51

0.7843137254901961

In [130]:
gaussian_model.score(x_test , y_test)

0.7843137254901961