In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Section :- A

#### 1. Create a NumPy array using random function?

In [2]:
A = np.random.rand(5)
A

array([0.0988176 , 0.66304507, 0.92684726, 0.14509466, 0.35468585])

#### 2. Print the average value in above NumPy array?

In [18]:
sum(A)/len(A)

0.43769808848709235

#### 3. Create a pandas dataframe from the python dictionary.

In [4]:
B = {
        'Name' : ['Joy' , 'Vicky' ,'James' , 'Anonymous'],
        'Age' : [25,26,21,23],
        'Blood Gr'  : ['A' , 'B' , 'O+' , 'A+']
    }

C = pd.DataFrame(B)
C

Name  Age Blood Gr
0        Joy   25        A
1      Vicky   26        B
2      James   21       O+
3  Anonymous   23       A+

#### 4. Rename one column from the above dataframe.

In [5]:
C.rename(columns={"Blood Gr" : 'Blood Group'})

Name  Age Blood Group
0        Joy   25           A
1      Vicky   26           B
2      James   21          O+
3  Anonymous   23          A+

## Section :- B

#### 1. Load the fracture.csv data into pandas dataframe.

In [6]:
MDF = pd.read_csv('fracture.csv')
MDF

id        age sex     fracture  weight_kg  height_cm      medication  \
0      469  57.052768   F  no fracture       64.0      155.5  Anticonvulsant   
1     8724  75.741225   F  no fracture       78.0      162.0   No medication   
2     6736  70.778900   M  no fracture       73.0      170.5   No medication   
3    24180  78.247175   F  no fracture       60.0      148.0   No medication   
4    17072  54.191877   M  no fracture       55.0      161.0   No medication   
..     ...        ...  ..          ...        ...        ...             ...   
164  21892  77.982543   M     fracture       74.0      164.0   No medication   
165  24140  50.285303   F     fracture       59.0      161.0   No medication   
166   6969  46.359721   M     fracture       67.0      169.0   No medication   
167   5505  54.788368   M     fracture       70.0      166.0   No medication   
168     71  69.994822   F     fracture       68.5      165.0   No medication   

     waiting_time     bmd  
0              18  0.8793  
1              56  0.7946  
2              10  0.9067  
3              14  0.7112  
4              20  0.7909  
..            ...     ...  
164            49  0.7941  
165             6  0.7971  
166            10  0.8037  
167            14  0.8072  
168            25  0.8664  

[169 rows x 9 columns]

#### 2. Add new column named “bmi” to store Body Mass Index for each record. Formula to calculate BMI is: weight_kg / (height_cm/100)^2

In [7]:
MDF['bmi'] = MDF['weight_kg'] / (MDF['height_cm'] / 100) ** 2
MDF

id        age sex     fracture  weight_kg  height_cm      medication  \
0      469  57.052768   F  no fracture       64.0      155.5  Anticonvulsant   
1     8724  75.741225   F  no fracture       78.0      162.0   No medication   
2     6736  70.778900   M  no fracture       73.0      170.5   No medication   
3    24180  78.247175   F  no fracture       60.0      148.0   No medication   
4    17072  54.191877   M  no fracture       55.0      161.0   No medication   
..     ...        ...  ..          ...        ...        ...             ...   
164  21892  77.982543   M     fracture       74.0      164.0   No medication   
165  24140  50.285303   F     fracture       59.0      161.0   No medication   
166   6969  46.359721   M     fracture       67.0      169.0   No medication   
167   5505  54.788368   M     fracture       70.0      166.0   No medication   
168     71  69.994822   F     fracture       68.5      165.0   No medication   

     waiting_time     bmd        bmi  
0              18  0.8793  26.467882  
1              56  0.7946  29.721079  
2              10  0.9067  25.111583  
3              14  0.7112  27.392257  
4              20  0.7909  21.218317  
..            ...     ...        ...  
164            49  0.7941  27.513385  
165             6  0.7971  22.761468  
166            10  0.8037  23.458562  
167            14  0.8072  25.402816  
168            25  0.8664  25.160698  

[169 rows x 10 columns]

#### 3. Split the data set in to test and train in 20:80 ratio.

In [8]:
x = MDF[['age' , 'sex' , 'bmi'  , 'bmd']]
y = MDF['fracture'].values

In [9]:
from sklearn.preprocessing import LabelEncoder

label_y = LabelEncoder()
y = label_y.fit_transform(y)


label_s = LabelEncoder()
x['sex'] = label_s.fit_transform(x['sex'])
x = x.values


C:\Users\VAIBHAV DARJI\AppData\Local\Temp\ipykernel_7900\420388755.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['sex'] = label_s.fit_transform(x['sex'])


In [10]:
x

array([[57.05276775,  0.        , 26.46788185,  0.8793    ],
       [75.7412248 ,  0.        , 29.7210791 ,  0.79460001],
       [70.7789    ,  1.        , 25.11158315,  0.90670002],
       [78.24717531,  0.        , 27.39225712,  0.7112    ],
       [54.1918766 ,  1.        , 21.21831719,  0.79089999],
       [77.17775151,  1.        , 23.03004535,  0.73009998],
       [56.18061769,  1.        , 30.45765595,  1.0096    ],
       [49.91613988,  0.        , 26.22222222,  0.73100001],
       [68.40840332,  1.        , 22.94811574,  0.6893    ],
       [66.25664804,  1.        , 28.30160867,  0.94660002],
       [45.86658172,  1.        , 21.70792339,  0.80150002],
       [73.97047074,  0.        , 25.2825699 ,  0.57929999],
       [60.55541712,  0.        , 31.63371488,  0.97600001],
       [64.2131031 ,  1.        , 29.3877551 ,  0.91839999],
       [53.3954402 ,  1.        , 26.50887574,  0.80199999],
       [66.82546218,  1.        , 25.99090318,  0.80330002],
       [57.93459324,  1.

In [11]:
from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(x,y , test_size=0.2)
print('original size :' , y.size)
print("train size :" , y_train.size)
print("test size :" , y_test.size)

original size : 169
train size : 135
test size : 34


#### 4. Build a SVM model to predict the fracture considering age, sex,bmi and bmd.

In [12]:
from sklearn.svm import SVC

svm_model = SVC(kernel='sigmoid')   #sigmoid , linear , poly , rbf
svm_model.fit(x_train , y_train)
y_pred = svm_model.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### 5. Apply the model on to the test and train data. Plot the outcomes of prediction using appropriate graph.

#### 6. Calculate accuracy of the model using confusion matix.

In [13]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test , y_pred)
26/34

0.7647058823529411

### use KNN

In [14]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(p=2 , n_neighbors=5 , metric='cosine')
knn_model.fit(x_train , y_train)
y_pred_2 = knn_model.predict(x_test)
y_pred_2

confusion_matrix(y_test , y_pred_2)
26/34

0.7647058823529411