In [45]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Section :- A

#### 1. Create a NumPy array from a list?

In [46]:
A = [5,2,3]
B = np.array(A)
B

array([5, 2, 3])

#### 2. Print the maximum and minimum value in above NumPy array?

In [47]:
print("Max :" ,max(B))
print("Min:" ,min(B))

Max : 5
Min: 2


#### 3. Create a pandas dataframe from the python dictionary.

In [48]:
C1 = ['Joy' , 'James' , 'Pollard']
C2 = [5,8,3]
C3 = ['A' , 'B' , 'D']

C = {
    'Name' : C1,
    'Roll No' : C2,
    'Division' : C3
    }

D = pd.DataFrame(C)
D


Name  Roll No Division
0      Joy        5        A
1    James        8        B
2  Pollard        3        D

#### 4. Delete one column from the above dataframe.

In [49]:
D.drop('Division' , axis=1) # axis=1 for columns
                            # axis=0 for rows

Name  Roll No
0      Joy        5
1    James        8
2  Pollard        3

## Section :- B

#### 1. Load the fracture.csv data into pandas dataframe and print first 15 record..

In [50]:
MDF = pd.read_csv('fracture.csv')
MDF.head(15)

id        age sex     fracture  weight_kg  height_cm       medication  \
0     469  57.052768   F  no fracture       64.0      155.5   Anticonvulsant   
1    8724  75.741225   F  no fracture       78.0      162.0    No medication   
2    6736  70.778900   M  no fracture       73.0      170.5    No medication   
3   24180  78.247175   F  no fracture       60.0      148.0    No medication   
4   17072  54.191877   M  no fracture       55.0      161.0    No medication   
5    3806  77.177752   M  no fracture       65.0      168.0    No medication   
6   17106  56.180618   M  no fracture       77.0      159.0    No medication   
7   23834  49.916140   F  no fracture       59.0      150.0    No medication   
8    2454  68.408403   M  no fracture       64.0      167.0  Glucocorticoids   
9    2088  66.256648   M  no fracture       72.0      159.5    No medication   
10   5364  45.866582   M  no fracture       62.0      169.0    No medication   
11   8922  73.970471   F  no fracture       68.0      164.0    No medication   
12  23890  60.555417   F  no fracture       76.0      155.0    No medication   
13   3047  64.213103   M  no fracture       90.0      175.0  Glucocorticoids   
14   2179  53.395440   M  no fracture       70.0      162.5    No medication   

    waiting_time     bmd  
0             18  0.8793  
1             56  0.7946  
2             10  0.9067  
3             14  0.7112  
4             20  0.7909  
5              7  0.7301  
6             26  1.0096  
7              9  0.7310  
8              6  0.6893  
9             10  0.9466  
10            12  0.8015  
11             5  0.5793  
12            11  0.9760  
13            28  0.9184  
14            73  0.8020

#### 2. Add new column named “bmi” to store Body Mass Index for each record. Formula to calculate BMI is: weight_kg / (height_cm/100)^2.

In [51]:
MDF['BMI'] = MDF['weight_kg'] / (MDF['height_cm'] / 100) ** 2
MDF

id        age sex     fracture  weight_kg  height_cm      medication  \
0      469  57.052768   F  no fracture       64.0      155.5  Anticonvulsant   
1     8724  75.741225   F  no fracture       78.0      162.0   No medication   
2     6736  70.778900   M  no fracture       73.0      170.5   No medication   
3    24180  78.247175   F  no fracture       60.0      148.0   No medication   
4    17072  54.191877   M  no fracture       55.0      161.0   No medication   
..     ...        ...  ..          ...        ...        ...             ...   
164  21892  77.982543   M     fracture       74.0      164.0   No medication   
165  24140  50.285303   F     fracture       59.0      161.0   No medication   
166   6969  46.359721   M     fracture       67.0      169.0   No medication   
167   5505  54.788368   M     fracture       70.0      166.0   No medication   
168     71  69.994822   F     fracture       68.5      165.0   No medication   

     waiting_time     bmd        BMI  
0              18  0.8793  26.467882  
1              56  0.7946  29.721079  
2              10  0.9067  25.111583  
3              14  0.7112  27.392257  
4              20  0.7909  21.218317  
..            ...     ...        ...  
164            49  0.7941  27.513385  
165             6  0.7971  22.761468  
166            10  0.8037  23.458562  
167            14  0.8072  25.402816  
168            25  0.8664  25.160698  

[169 rows x 10 columns]

#### 3. Split the data set in to test and train.

In [52]:
x = MDF[['age' , 'sex' , 'bmd' , 'BMI']]
x


y = MDF['fracture'].values

In [53]:
from sklearn.preprocessing import LabelEncoder
label_y = LabelEncoder()
y = label_y.fit_transform(y)
y

label_s = LabelEncoder()
x['sex'] = label_s.fit_transform(x['sex'])
x

C:\Users\VAIBHAV DARJI\AppData\Local\Temp\ipykernel_17424\1093710954.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['sex'] = label_s.fit_transform(x['sex'])


age  sex     bmd        BMI
0    57.052768    0  0.8793  26.467882
1    75.741225    0  0.7946  29.721079
2    70.778900    1  0.9067  25.111583
3    78.247175    0  0.7112  27.392257
4    54.191877    1  0.7909  21.218317
..         ...  ...     ...        ...
164  77.982543    1  0.7941  27.513385
165  50.285303    0  0.7971  22.761468
166  46.359721    1  0.8037  23.458562
167  54.788368    1  0.8072  25.402816
168  69.994822    0  0.8664  25.160698

[169 rows x 4 columns]

In [54]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size=0.3)

In [55]:
y_train.size
y_test.size

51

#### 4. Build a logistic regression model to predict the fracture considering age, sex, bmi and bmd.

In [56]:
from sklearn.linear_model  import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train , y_train)

y_pred = logmodel.predict(x_test)
y_pred

array([1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1])

#### 5. Apply the model on to the test and train data. Plot the outcomes of prediction using appropriate graph.

#### 6. Calculate accuracy of the model using confusion matix.

In [60]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test ,y_pred)

array([[ 7, 10],
       [ 1, 33]], dtype=int64)

In [70]:
40/51

0.7843137254901961

In [58]:
logmodel.score(x_test ,y_test)

0.7843137254901961